# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.13.0"

default_platform :ios

platform :ios do
  before_all do
    # carthage
  end

  lane :build do
    [
      "TwoWayBind",
      "Stopwatch",
      "HandleError",
      "Questions",
      "PDFExpertContents",
      "RxDataSourcesExample",
      "CustomRefresh",
      "TextInput",
      "UploadImages",
      "YepRecord",
      "Concurrency",
      "GitHubSearchRepositoriesX",
      "Form",
      "UploadImageSimple",
      "LocalAuthenticationDemo"
    ].each do |scheme|
      xcodebuild(scheme: scheme, project: "rx-sample-code.xcodeproj")
    end
    # gym(project: "rx-sample-code.xcodeproj")
    # xcodebuild(scheme: "HandleError", project: "rx-sample-code.xcodeproj")
  end

end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
